### ISSUE TITLE
Correzione Piano di Qualifica

### ISSUE THREAD

**Issue by davide97g** [dreamcorpsw/bayesian-grafana-plugin#10]
Correzioni da fare per il piano di qualifica **entro il 24/03.**

- [x] §1.4: fate grande confusione tra tipi di riferimenti e ripetete la stessa voce sotto categorie diverse. 
- [ ] §2-§3-§4: _si coglie il tentativo di recepire le raccomandazione ricevute in sede di RR,_ ma anche grande confusione, superficialità e inconsistenza nella sua attuazione. 
- [ ] Il risultato è un documento che resta deludente per chi lo legge, frustrante per chi lo redige, e poco comprensibile per chi lo verifica.

**Comment by PietroCasotto** [comment]
§2-§3-§4 non capiamo cosa vuole da noi, il 19/04 provo a chiedere che ca**o vuole da noi

**Comment by PietroCasotto** [comment]
Ho parlato con il prof... lui dice che il documento sembra tanto un qualcosa fatto perchè "si doveva fare" e fatto velocemente, senza pensare alle cose. Penso si riferisca alla grande quantità di test (di validazione) che abbiamo messo che si vanno a sovrapporre tra di loro, facendo fare un sacco di volte il lavoro, poi se voi volete chiedere altre delucidazioni al prof, fate pure
