### ISSUE TITLE
Correzione Analisi dei Requisiti

### ISSUE THREAD

**Issue by davide97g** [dreamcorpsw/bayesian-grafana-plugin#7]
Correzioni e modifiche da apportare all'analisi dei requisiti, **entro il 24/03.**
- [x] UC_generale contiene casi d’uso che non possono condividere fra loro le medesime pre e post condizioni: eliminare, o ridurne l’ambito. -->cancellata
- [x] UC1(A) e UC1(B) non sono sotto-casi di UC1, ma concretizzazioni: per essi va dunque usata l’ereditarietà.-->vedere nuova descrizione delle (A), (B), ecc e UML caso d'uso general.
- [x] UC1(A).1 non porta alcun valore aggiunto all’analisi. -->cancellato
- [x] UC3.1 non è sotto-caso di UC3. -->3.1 diventa indipendente, cioe uc4
- [x] UC3.2 e i suoi sotto-casi devono essere rivisti utilizzando l’ereditarietà.--> vedere nuova descrizione delle (A), (B), ecc e UML caso d'uso 3.
- [x] UC3.2(A) e UC3.2(B) contengono un sotto-caso di visualizzazione che non è corretto.--> cancellati i sottocasi di visualizzazione.
- [x] UC4.1 non è un caso d’uso: dov’è la sua estensione? -->4.1 cancellato e aggiornato l'uml
- [x] Anche UC5 va rivisto, focalizzandosi sulle informazioni necessarie per la definizione di un panel.
- [x] Figura 14: “Modifica di un aler”; questo errore è segno di verifica insufficiente.
- [x] UC10: i due sotto-casi sono identici (medesimo nome). 
- [x] I nomi nel diagramma non corrispondono a quelli usati nelle descrizioni. 
- [x] UC13 e i suoi sotto-casi sono da rivedere completamente. --> tolto uc1 come sottocaso
- [x] I requisiti funzionali devono essere approfonditi in maggior dettaglio. 
- [x] RVC1: quale versione di Js? RVC2 è requisito di qualità. Inoltre, a quale tipo di licenza volete fare riferimento?
- [x] Traslare i numeri dei casi d' uso.
- [x] Manca il tracciamento requisiti funzionali - casi d’uso, che va fornito obbligatoriamente. 
- [x] Correggere fig.13 di UC11 con il nome di UC12 aggiornato a "Apertura tab "Alert"".
- [x] Correggere fig.20 di UC15 con il nome di UC12 aggiornato a "Apertura tab "Alert"".
- [x] UC2 è descritto come diagramma di attività. In realtà, mi sarei aspettato una lista delle informazioni effettivamente modificabili. 
- [x] Alcune immagini devono avere come descrizione 'schema generale'

Discreto il livello di dettaglio raggiunto nell'analisi, che resta però insufficiente per i requisiti funzionali.
I casi d’uso contengono molti errori che devono essere sanati.
Manca il tracciamento.

**Comment by matbord** [comment]
Possibili aggiunte:
-Creazione di un panel;
-Creazione di una dashboard;
-Eliminazione dashboard;
-Eliminazione panel;
-Riordinamento panel;
-Visualizzazione grafici dei nodi non monitorati;

**Comment by davide97g** [comment]
Personali considerazioni su queste aggiunte.
Non mi sembra sensato occuparsi della creazione ed eliminazione della dashboard quando è a discrezione della piattaforma quel compito. 
Per quanto riguarda la visualizzazione può andare.
Il riordinamento per lo stesso motivo della dashboard.
La creazione di un panel è una precondizione e non una funzionalità del nostro plug-in, così come per l'eliminazione.
Sono solo mie considerazioni

**Comment by matbord** [comment]
Casi d'uso conclusivi da aggiungerre:
-Visualizzazione grafici dei nodi non monitorati;
-Collegamento con il database;

**Comment by davide97g** [comment]
Aggiunti:
- collegamento db
- dati della rete
- creazione dashboard
- eliminazione dashboard
- creazione panel
- eliminazione panel
- visualizzazione grafici non monitorati

**Comment by davide97g** [comment]
C'è un errore nel UC12. Il nome appropriato non è "panel" ma "tab".
Scrivo solo per aiutare alla miglior comprensione di quello che sarà il nostro prodotto finale.
Infatti un utente in fase di modifica di un _panel_ può andare nella _tab_ "Alert" e non in un panel "Alert".
In teoria non ci dovrebbero essere errori a catena e dovrebbe essere contingente. 
E' stato modificato.

**Comment by davide97g** [comment]
Mi correggo, c'è un errore quindi nella fig.13 che descrive UC11.

**Comment by davide97g** [comment]
Mi viene un dubbio sull'impostazione dei nostri casi d'uso.
Non sono convinto che esprimere anche la più atomica azione dell'utente sia il modo corretto di lavorare per l'analisi.
L'esplicitazione dei requisiti funzionali ha questo compito secondo me.
Da un caso d'uso che offre una funzionalità, per esempio il configurare le informazioni di un alert, estraggo i requisiti per poter implementare quella funzionalità: ora elenco una per una tutte le informazioni che mi servono per definire un alert e le esplicito grazie ai requisiti.
Se fosse in questo modo andrebbe rivista l'analisi dei requisiti a fondo, decisamente, che richiederebbe almeno altre 4/5 ore.
Per ora Cardin non ci ha commentato negativamente questa mia nota, quindi spero non sia così. Però dall'analisi più precisa dei requisiti c'è qualcosa che non torna.
