### ISSUE TITLE
Correzione Norme di Progetto

### ISSUE THREAD

**Issue by davide97g** [dreamcorpsw/bayesian-grafana-plugin#8]
Correzioni da fare sulle norme di progetto **entro il 24/03.**

- [x] §1.5: adottare lo standard ISO/IEC 12207 come riferimento normativo è inopportuno, perché certamente non riuscirete a soddisfarlo per davvero. È più realistico trattarlo come riferimento informativo. 
- [x] Le Norme informano PdP e PdQ; non ha senso dunque che questi ultimi vi appaiano tra i riferimenti informativi, perché la loro presenza causa un riferimento circolare. 
- [x] §2.1: Il processo di fornitura include assai più attività per voi significative rispetto a quelle che avete indicato. L’ignorarle o il collocarle altrove segnala insufficiente comprensione dei processi coinvolti. 
- [x] §2.2.2.6: il termine “Sviluppo” designa il corrispondente processo primario e non può essere utilizzato per designare una attività di esso. 
- [x] §2.2.2.7: CI, propriamente, non è una attività ma una metodologia applicata allo sviluppo. 
- [ ] §4: **(come già segnalato in sede di RR)** l’organizzazione dei contenuti di questa sezione continua a essere confusa e non conforme allo standard di riferimento.
- [x] §A: **(come già segnalato in sede di RR)** persiste il difetto di comprensione.

Nel complesso, qualche miglioramento nei contenuti; 
permangono difetti di struttura e di interpretazione.

**Comment by PietroCasotto** [comment]
§A: Forse questo fa riferimento anche al fatto che non abbiamo inserito nulla nel PdQ che riguarda questo aspetto... Forse è anche per questo che ci ha detto che il PdQ è "deludente per chi lo legge"
